work_dir: /home/wuyushan/project1/AimCLR/data/gty/AAAI_github/ntu60_cs/aimclr_bone/finetune_eval

weights: /home/wuyushan/project1/AimCLR/data/gty/released_model/ntu60_xsub_bone.pt
# weights: /home/wuyushan/project1/AimCLR/data/gty/released_model/pkup1cs_bone.pt
# weights: /data/gty/AAAI_github/ntu60_cs/aimclr_bone/pretext/epoch300_model.pt
ignore_weights: [encoder_q.fc, encoder_k, queue]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /home/wuyushan/project1/AimCLR/data/gty/pku_part1_frame50/xsub/train_position.npy  # /data/gty/action_dataset/ntu60_frame50/xsub/train_position.npy
  label_path: /home/wuyushan/project1/AimCLR/data/gty/pku_part1_frame50/xsub/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /home/wuyushan/project1/AimCLR/data/gty/pku_part1_frame50/xsub/val_position.npy
  label_path: /home/wuyushan/project1/AimCLR/data/gty/pku_part1_frame50/xsub/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.aimclr.AimCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 51  # PKUMMD
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d' 
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.01
optimizer: SGD
step: [250]

# training
device: [1]  # 2
batch_size: 64  # 128
test_batch_size: 64  # 128
num_epoch: 100
stream: 'bone'

# log
save_interval: -1
eval_interval: 5
